README.md
Missing the mandatory `:hash:` in the middle
=> Fix hash example

index.js
the missing semicolon yields warning in lint tools.
=> adding missing semicolon

README.md, index.js, test/optional-file-emission.test.js
When building server side packages there may be no need to emit a file;
this makes file emission optional, while keeping the default behaviour
as is.
Resolves #59
=> Make emitting a file optional.

index.js
Remove `var path = require("path");` because it's not used anywhere in the source.
=> Remove unused dependency

README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra
=> Add -loader suffix to README to reflect new loader syntax webpack 2 requirement

.github/assets/file_loader_icon.svg, README.md
Updates Readme to the Webpack standard format per @TheLarkInn in webpack/webpack#3195
> header image is a rawgit url that will resolve when the attached image lands in master.
=> chore(readme): Update to webpack standard format

README.md
**What kind of change does this PR introduce?**
Fix Maintainer section HTML
**Did you add tests for your changes?**
No
**If relevant, did you update the README?**
Yes
**Summary**
Maintainers section HTML was incorrect, making the website look like this:
After the change it looks like this:
=> Fix Maintainers section look

CHANGELOG.md, package.json
As discussed in webpack/webpack#4104
- Adds standard-version
- Release docs now in https://webpack.js.org/development/release-process/
- Adds empty changelog ( will require some `reword` work to get the full history )
=> chore(release): add standard version & documentation

index.js, test/correct-filename.test.js
**What kind of change does this PR introduce?**
bugfix -  The new useRelativePath option code - did not handle the case where you used a function for the outputPath generation. 
**Did you add tests for your changes?**
Yes - I added in a test to make sure that if you use a function for outputPath it is called. If you use the useRelativePath it is ignored.
**If relevant, did you update the README?**
You don't currently document using outputPath as a function so I wasn't sure I should.
**Summary**
New code broke old behavior. If you use a function to set the outputPath it was expected that the function would be the decider on where the output of the file is.  Recent code took that away:(
Motivation: Recent code broke old behavior. I updated to the current version and my app stopped …
=> fix: outputPath function overriden by useRelativePath

index.js, test/correct-filename.test.js
**What kind of change does this PR introduce?**
Bugfix.
**Did you add tests for your changes?**
Yes.
**Summary**
When checking if the publicPath option was set, it would only do a falsy check which would return false with an empty string. Modified it to also set the public path if an empty string is given.
**Does this PR introduce a breaking change?**
No.
**Other information**
=> fix: allow to override publicPath with an empty string

index.js
**What kind of change does this PR introduce?**
bugfix
**Did you add tests for your changes?**
**If relevant, did you update the README?**
**Summary**
Initializing `publicPath` to false was preventing the new option from being used with `webpack-config-validator
`
See comment in #145
**Does this PR introduce a breaking change?**
No
**Other information**
Fixes #158
=> fix: init `publicPath` to undefined

src/index.js, test/correct-filename.test.js
The refactoring to ES modules (#167) accidentally left an `=` in the default export, which is a syntax error.
=> fix: remove `=` from default export (`SyntaxError`)

README.md
Closes https://github.com/webpack-contrib/file-loader/issues/192
> Edited by @michael-ciniawsky (Formatting)
=> docs(README): add missing commas in examples

package-lock.json, package.json, src/index.js, src/options.json, test/Errors.test.js, test/__snapshots__/Errors.test.js.snap, test/emitFile.test.js, test/loader.test.js
This PR removes the obsolete options handling for `this.options.fileLoader` (`webpack =< v1.0.0`)
**webpack.config.js**
```js
const config = {
module: {
loaders: [
{ 
test: /\.(png|jpg)$/,
loader: 'file-loader'
}
]
},
fileLoader: {...options} // Invalid in webpack >= v2.0.0
}
```
=> feat: add `options` validation (`schema-utils`)

src/cjs.js, test/cjs.test.js
We use `"main": "dist/cjs.js"` in `package.json`, but `default`(https://github.com/webpack-contrib/file-loader/blob/master/src/cjs.js#L1) doesn't contain `raw` value so `file-loader` doesn't work correctly.
=> fix(cjs): export `raw` value

src/index.js, test/loader.test.js
---
`css-loader` sadly expects CJS exports for asset resolving and there isn't a convenient way to fix it directly in `css-loader` atm. ES2015 Modules exports will have to wait until the new CSS Pipeline is in place or a major version bump in `css-loader` is accepted. Note that CJS <=> ESM doesn't really matter here since we export **one** static value (`Filepath {String}`) only anyways.
---
- Fixes #211 
- Fixes #181
=> fix(index): revert to CJS exports

README.md
The current documentation is incorrect, or at least misleading. For `publicPath` or `outputPath`, if you omit the leading slash, no directory is created, and the files are placed in `output.path` as usual.
If this is the desired behavior, it should be documented as such; if it's not, I'm happy to submit a PR to `file-loader` which would make it care less about whether there's a trailing slash.
=> docs(README): add missing leading slash in examples

src/options.json, test/Errors.test.js, test/__snapshots__/Errors.test.js.snap
---
[loaderUtils#interpolateName](https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L27) accepts a `{Function}` for `name`
---
- Fixes #215
=> fix(schema): allow `name` to be a `{Function}` (`options.name`)

README.md
It seems the default is 9999:
https://github.com/webpack/loader-utils/blob/master/lib/getHashDigest.js#L41
=> docs(README): correct the default value for `[hash:<length>]`

src/index.js
=> fix(index): add `this.rootContext` for `webpack >= v4.0.0` compatibility

README.md
I noticed that `hex` was the default value with the `hash` placeholder, not the documented `base64`. This change updates the documentation to reflect that.
=> docs(README): correct default value for `digestType` (`hashes`)

README.md
Hello,
This PR describes the behavior of `regExp` and how to use it.  
I've also fix :  
- the type of the placeholder `[N]`, hope this doesn't alter too much your table layout.
- regExp is not a query parameter, it's an option. Moreover, passing a regExp as a query param is not a good idea, escaping is way too complicated.
Hope you will like it. :smile:
=> docs(README): add `regExp` option (`options.regExp`)

src/index.js, test/options/__snapshots__/outputPath.test.js.snap, test/options/__snapshots__/publicPath.test.js.snap, test/options/outputPath.test.js, test/options/publicPath.test.js
=> fix(index): don't concat `options.outputPath` and `options.publicPath`

src/index.js, test/options/__snapshots__/publicPath.test.js.snap, test/options/publicPath.test.js
- Fixes #252
Since `publicPath` can be a full URL (which can contain protocols), using `path.join()` to concat file paths isn't sufficient here
=> fix(index): handle protocol URL's correctly (`options.publicPath`)

src/index.js
- Fixes #251 
Use `path.posix` instead of `path` to avoid platform specifics of the `path` module to keep paths consistent
- #253  (Ideally lands before this PR)
=> fix(index): use `path.posix` for platform consistency

README.md
Update README to clarify that file-loader is working with Webpack v3.
Closes #284.
No.
=> docs(readme): clarify support for Webpack v3

README.md, package.json, src/index.js
BREAKING CHANGE: drop support for webpack < 4
Drop support webpack <4
Yes
No
=> refactor: drop support for webpack < 4

README.md, src/index.js, test/__snapshots__/outputPath-option.test.js.snap, test/__snapshots__/publicPath-option.test.js.snap, test/outputPath-option.test.js, test/publicPath-option.test.js
Allow to developers have original asset path
No
No
=> feat: `resourcePath` is now available in `outputPath` and `publicPath`

README.md, src/index.js, test/__snapshots__/outputPath-option.test.js.snap, test/__snapshots__/publicPath-option.test.js.snap, test/outputPath-option.test.js, test/publicPath-option.test.js
Pass `context` to function
No
No
=> feat: `context` is now available in `outputPath` and `publicPath`

README.md
Ref: issue #314 
This PR aims to update the doc to reflect use of `Rule.loader` and `Rule.use` in the case of using single (rather than multiple) loaders. This being said, Webpack official docs only deprecated the use of `Rule.loaders` rather than `Rule.loader`. In particular, it pointed out that `Rule.loader` can be used as a shortcut to `Rule.use: [ { loader } ]` (as seen in the following screenshot):
However most loaders have updated their docs to consistently use `Rule.use` rather than `Rule.loader` even in the case of using a single loader:
[https://webpack.js.org/loaders/babel-loader/](https://webpack.js.org/loaders/url-loader/)
[https://webpack.js.org/loaders/babel-loader/](https://webpack.js.org/loaders/url-loader/)
No breaking changes
N/A
fixes #314
=> docs(README): replaced Rule.loader with Rule.use in single loader examples

README.md, src/index.js, test/__snapshots__/esModules-option.test.js.snap, test/esModules-option.test.js
Using the old CommonJS module syntax breaks some optimizations that Webpack does in newer versions, like tree shaking and module concatenation. This flags allows the output to be ES2015 modules if enabled.
Default is `false`, so it shouldn't break anything unless used.
=> New options flag to output ES2015 modules

README.md
=> docs: fix the description of the `esModule` option

package-lock.json, src/options.json, test/__snapshots__/validate-options.test.js.snap
Added 'description' field on esModule option.
=> fix(schema): added description on esModule

README.md, package-lock.json, package.json, src/index.js, test/__snapshots__/emitFile-option.test.js.snap, test/__snapshots__/esModule-option.test.js.snap, test/__snapshots__/loader.test.js.snap, test/__snapshots__/name-option.test.js.snap, test/__snapshots__/outputPath-option.test.js.snap, test/__snapshots__/postTransformPublicPath-option.test.js.snap, test/__snapshots__/publicPath-option.test.js.snap, test/outputPath-option.test.js, test/publicPath-option.test.js
BREAKING CHANGE: use `md4` by default for hashing
Use `md4` by default for perf reasons
Yes
No
=> chore(deps): update

src/index.js, test/name-option.test.js
Passes an `immutable` flag through assetInfo which other plugins may use.
https://github.com/webpack-contrib/file-loader/issues/382
=> feat: pass immutable info on files

src/index.js, test/name-option.test.js
hash in query and fragment do not do asset immutable
No
No
=> fix: immutable flag when the `name` option have hash in query string
